development:
  cloud_name: dlbnj8ots
  api_key: '528824891487233'
  api_secret: bWLKtLk7Ds9RGejVZI0jM6Cl26c
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dlbnj8ots
  api_key: '528824891487233'
  api_secret: bWLKtLk7Ds9RGejVZI0jM6Cl26c
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dlbnj8ots
  api_key: '528824891487233'
  api_secret: bWLKtLk7Ds9RGejVZI0jM6Cl26c
  enhance_image_tag: true
  static_image_support: false
